# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-01-29 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
