# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-01-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20250129_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre 2222'),
        ),
    ]
