# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='imagen'),
            preserve_default=False,
        ),
    ]
