# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20250206_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='imagen'),
        ),
    ]
