# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-06 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20250206_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='mascota_imgs'),
        ),
    ]
