# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-02-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20250206_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascota_imgs'),
        ),
    ]
